### PR TITLE
Travis (container based install) and Flake8 corrections

### LINKED ISSUE #29: Travis - fix SEG-Y test (works locally).

### PR DESCRIPTION
**Pull request by fmilthaler**
This commit adds a container based travis setup and adds flake8 style corrections.
This closes #29 and #34

### CODE REVIEW

**Comment by fmilthaler** [comment]
The first two tests are passing, the third (mpi) is failing. This is currently broken in master as well.

**Comment by ggorman** [comment]
@fmilthaler - can you resolve the conflicts?

**Comment by fmilthaler** [comment]
Dont push yet. Need to sort out flake8 things again

**Comment by fmilthaler** [comment]
Ok, this is good to go now. Still passing test 1 & 2, and failing test 3 (mpi) with the same error as in master.

**Pull request merged**
