### PR TITLE
Adding binary reader class

### PR DESCRIPTION
**Pull request by fmilthaler**
Adding a generic binary reader.

### CODE REVIEW

**Comment by mlange05** [comment]
In general this looks sensible. Do we have any way of testing this?

**Comment by fmilthaler** [comment]
Yes, there are 3 data files stored in the "data" repo I used for testing purposes: SmoothM.lfs, TrueM.lfs, data.lfs.
Those files were pushed via git-lfs. Follow the instructions in the updated README of the data repo (check the pull request).
I can add a travis config file and a test for this.

**Comment by mlange05** [comment]
A small travis test would be great, just load and ensure the final data has the right shape.

**Comment by fmilthaler** [comment]
Test is included, works locally. Travis needs a bit more sorting out due to the git-lfs --> git-fat issue as described in opesci/data. 
As agreed with @ggorman earlier, this can go into master now. As soon as travis/git-lfs/git-fat is sorted out, the binreader will be tested.

**Pull request merged**
